name: Build Push Deploy Frontend

on:
  push:
    branches: [ "main" ]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

      - name: Build
        run: docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/servesmart-frontend:latest .

      - name: Push
        run: docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/servesmart-frontend:latest
